import { Colors, Spacing, Type } from "../tokens/theme.slint";

/// L ab el component.
export component Label inherits HorizontalLayout {
    /// Input property "text".
    in property <string> text: "";
    /// Input property "required".
    in property <bool>   required: false;
    /// Input property "disabled".
    in property <bool>   disabled: false;

    /// Private property "half-xs" used internally.
    private property <length> half-xs:  Spacing.xs / 2;
    /// Private property "req-mark" used internally.
    private property <string> req-mark: " *";

    spacing: root.half-xs;

    Text {
        text: root.text;
        font-size: Type.caption-size;
        color: root.disabled ? Colors.text-disabled : Colors.text-secondary;
        vertical-alignment: center;
    }

    if root.required: Text {
        text: root.req-mark;
        font-size: Type.caption-size;
        color: Colors.error;
        vertical-alignment: center;
    }
}
