import { Colors, Spacing, Type } from "../globals/theme.slint";
import { Variants } from "../state/variants.slint";

/// B ad ge component.
/// component `Badge`.
export component Badge inherits Rectangle {
    /// Input property "text".
    /// property `text`.
    in property <string> text: "";
    /// Input property "variant".
    /// property `variant`.
    in property <string> variant: "info";   // info | success | warning | error

    height: Type.caption-size + Spacing.sm;
    border-radius: Spacing.xs;
    horizontal-stretch: 0;

    background:
        variant == Variants.success ? Colors.success :
        variant == Variants.warning ? Colors.warning :
        variant == Variants.error   ? Colors.error :
        Colors.accent;

    HorizontalLayout {
        alignment: center;
        padding-left: Spacing.sm;
        padding-right: Spacing.sm;

        Text {
            text: root.text;
            font-size: Type.caption-size;
            font-weight: Type.weight-semibold;
            color: Colors.accent-text;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}
