// Material 3 type scale.
// Reference: https://m3.material.io/styles/typography/type-scale-tokens

import { Settings } from "../../state/settings.slint";

export global MaterialType {
    // Display
    out property <length> display-large:  Settings.zoom * Settings.font-scale * 57px;
    out property <length> display-medium: Settings.zoom * Settings.font-scale * 45px;
    out property <length> display-small:  Settings.zoom * Settings.font-scale * 36px;

    // Headline
    out property <length> headline-large:  Settings.zoom * Settings.font-scale * 32px;
    out property <length> headline-medium: Settings.zoom * Settings.font-scale * 28px;
    out property <length> headline-small:  Settings.zoom * Settings.font-scale * 24px;

    // Title
    out property <length> title-large:  Settings.zoom * Settings.font-scale * 22px;
    out property <length> title-medium: Settings.zoom * Settings.font-scale * 16px;
    out property <length> title-small:  Settings.zoom * Settings.font-scale * 14px;

    // Body
    out property <length> body-large:  Settings.zoom * Settings.font-scale * 16px;
    out property <length> body-medium: Settings.zoom * Settings.font-scale * 14px;
    out property <length> body-small:  Settings.zoom * Settings.font-scale * 12px;

    // Label
    out property <length> label-large:  Settings.zoom * Settings.font-scale * 14px;
    out property <length> label-medium: Settings.zoom * Settings.font-scale * 12px;
    out property <length> label-small:  Settings.zoom * Settings.font-scale * 11px;

    // Weights
    out property <int> weight-regular: 400;
    out property <int> weight-medium:  500;
    out property <int> weight-bold:    700;
}
