name: Publish to crates.io

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build library
        run: cargo build -p slint-ui-templates

      - name: Run tests
        run: cargo test -p slint-ui-templates

      - name: Dry run publish
        run: cargo publish --dry-run -p slint-ui-templates

      - name: Publish to crates.io
        run: cargo publish -p slint-ui-templates --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
